[package]
name = "hello_world"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rocket = "=0.5.0-rc.3"

[dependencies.rocket_dyn_templates]
version = "=0.1.0-rc.3"
features = ["tera"]